# Generated by Django 5.0.2 on 2024-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBackend', '0003_alter_customeruser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
