# Generated by Django 5.0.2 on 2024-02-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBackend', '0004_blogdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
