# Generated by Django 5.0.2 on 2024-02-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBackend', '0005_alter_blogdata_content_alter_blogdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
