# Generated by Django 5.0.2 on 2024-02-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBackend', '0006_alter_blogdata_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='published_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
