# Generated by Django 5.0.2 on 2024-02-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBackend', '0007_alter_blogdata_published_date_alter_blogdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='authorPic',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
