# Generated by Django 5.0.2 on 2024-02-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBackend', '0008_blogdata_authorpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='authorPic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
