# Generated by Django 4.2.4 on 2024-02-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBackend', '0009_alter_blogdata_authorpic_alter_blogdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
